title: BioInformatique appliquée à la biologie des plantes (L3, année 2025-2026)
description: Apprendre à explorer des données et faire des graphiques sur R
show_downloads: true
theme: jekyll-theme-cayman
